### ISSUE TITLE
Reading multiple module

### ISSUE THREAD

**Issue by stanleyseow** [futomi/node-alps#2]
Hi,
How do I read multiple discovered modules one after another  ??

I managed to get the id for 2 modules but I'm unsure how to use the Promise to connect to the device2 but get this error :- 

id  : 48f07b78431f
topic : aa/sensor/48f07b78431f
rssi: -76

id2  : 48f07b78431d
topic : aa/sensor/48f07b78431d
rssi: -85

(node:20967) UnhandledPromiseRejectionWarning: Error: WRITE TIMEOUT (0x01)
    at Timeout.setTimeout (/home/pi/node_modules/node-alps/lib/modules/device.js:330:11)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:20967) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20967) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The complete codes are listed here ... 
https://pastebin.com/tD4VsNd4

**Comment by futomi** [comment]
Try the sample code below. The code successfully worked on Ubuntu 18.

```javascript
'use strict';
const Alps = require('node-alps');
const alps = new Alps();
let device1 = null;
let device2 = null;

alps.init().then(() => {
  console.log('Discovering devices...');
  return alps.discover({duration: 5000});
}).then((device_list) => {
  console.log(device_list.length + ' devices were found.');
  if(device_list.length < 2) {
    throw new Error('Turn on at least 2 devices.');
  }
  device1 = device_list[0];
  device2 = device_list[1];

  console.log('[Device1] Connecting...');
  return device1.connect();
}).then(() => {
  console.log('[Device1] Starting to monitor...');
  return device1.startMonitor({
    mode    : 0,
    interval: 1
  });
}).then(() => {
  console.log('[Device1] Started to monitor.');
  device1.onnotify = (data) => {
    console.log('[Device1] ' + JSON.stringify(data));
  };
  return waitPromise(10);
}).then(() => {
  console.log('[Device1] Stopping to monitor...');
  return device1.stopMonitor();
}).then(() => {
  console.log('[Device1] Disconnecting...');
  return device1.disconnect();
}).then(() => {
  console.log('[Device2] Connecting...');
  return device2.connect();
}).then(() => {
  console.log('[Device2] Starting to monitor...');
  return device2.startMonitor({
    mode    : 0,
    interval: 1
  });
}).then(() => {
  console.log('[Device2] Started to monitor.');
  device2.onnotify = (data) => {
    console.log('[Device2] ' + JSON.stringify(data));
  };
  return waitPromise(10);
}).then(() => {
  console.log('[Device2] Stopping to monitor...');
  return device2.stopMonitor();
}).then(() => {
  console.log('[Device1] Disconnecting...');
  return device2.disconnect();
}).then(() => {
  console.log('Success!');
  process.exit();
}).catch((error) => {
  console.error(error);
});

function waitPromise(sec) {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, sec * 1000);
  });
  return promise;
}
```

**Comment by stanleyseow** [comment]
Thanks a lot, I will test it out the soonest ....

**Comment by stanleyseow** [comment]
Thanks ...

**Comment by stanleyseow** [comment]
I solve this "reading multiple sensors" by accepting id as a command line argument and runs a crontab command line to be called every few minutes.
