### ISSUE TITLE
Getting data with many dataIndex

### ISSUE THREAD

**Issue by stanleyseow** [futomi/node-alps#3]
Hi,

When I pull data from the SNM, I m getting multiple dataIndex , how do I get ONLY 1 dataIndex or just the last dataIndex only .. or how to I request for one dataIndex only.

I've set the mode 1 interval to max value of 999.
        return device1.startMonitor({
                mode: 1,
                interval:999
                });

I have also deleted the timeStamp.   
delete data.timeStamp;

Thanks

Below the the sample output :

aa/sensor/48f07b78431d {
  "geoMagnetic": {
    "x": 28.95,
    "y": 25.2,
    "z": -241.35
  },
  "acceleration": {
    "x": 0.028564453125,
    "y": -0.00439453125,
    "z": -1.01220703125
  },
  "dataIndex": 13,
  "name": "48f07b78431d",
  "rssi": -77
}
aa/sensor/48f07b78431d {
  "geoMagnetic": {
    "x": 28.5,
    "y": 25.5,
    "z": -241.2
  },
  "acceleration": {
    "x": 0.028564453125,
    "y": -0.00439453125,
    "z": -1.021728515625
  },
  "dataIndex": 14,
  "name": "48f07b78431d",
  "rssi": -77
}

**Comment by futomi** [comment]
> When I pull data from the SNM, I m getting multiple dataIndex 

Really? As far as I can see your sample output, each data has only one `dataIndex`.
The `onnotify` event handler can receive only one data.

I think that the `onnotify` event handler received the 2 data at a very short interval.
Never expect that you can receive data precisely at the interval you set to the `interval` parameter.
Actual interval will fluctuate greatly.

Cheers,
Futomi
