### ISSUE TITLE
Pulling motion data in higher speed

### ISSUE THREAD

**Issue by stanleyseow** [futomi/node-alps#4]
Like the ALPS Android app, it can pull the motion data ( accel / geomagnetic ) very fast internal, can this be done on the nodejs version ?

Currently the onnotify is very slow when pulling the sensor data.

Thanks

**Comment by futomi** [comment]
What parameters did you pass to the `startMonitor()` method?
If you obtain the motion data, the `mode` has to be set to `1`. You can set the interval as well.

```javascript
device.startMonitor({
  mode: 1, // Motion Sensors
  interval: 200, // msec
});
```

The code above works well in my environment (Ubuntu + BLE dongle).

**Comment by stanleyseow** [comment]
Oh thanks..., what I mean was keep the connection open and allow the data to flow in non-stop without closing the connection...

Now it seems to be a request, wait a few seconds, all comes in , in 3 dataIndex , then closed the connection...

Sorry, I m very new to node.js..

**Comment by stanleyseow** [comment]
I figured this out below, I was able to pull the data, post to a mqtt server and use another js to pull the data and plot the x,y,z, in almost realtime...

the setTimeout() closed the connection , once I removed this, the connection did not disconnect...
